spring:
  application:
    name: config-client-b

server:
  port: 8002
  
logging:
  file:
    name: /var/tmp/logs/config-client-b/config-client-b
  level:
    root: INFO
    poc.springcloud: DEBUG

app:
  kv:
    k1: dev1
    k2: dev2  